openapi: 3.0.3
info:
  title: ChatApp
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/message:
    get:
      summary: ''
      operationId: getApiV1Message
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: number
                  description: 'Must be at least 10. Must not be greater than 50.'
                  example: 24
                page:
                  type: number
                  description: 'Must be at least 1.'
                  example: 3
              required:
                - to
                - page
      security: []
    post:
      summary: ''
      operationId: postApiV1Message
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  description: 'Must be at least 4 characters. Must not be greater than 255 characters.'
                  example: gxuhfumxnwc
              required:
                - body
      security: []
  '/api/v1/message/{uuid}':
    get:
      summary: ''
      operationId: getApiV1MessageUuid
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiV1MessageUuid
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  description: 'Must be at least 4 characters. Must not be greater than 255 characters.'
                  example: zjwvvdirboncxmjw
              required:
                - body
      security: []
    delete:
      summary: ''
      operationId: deleteApiV1MessageUuid
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: uuid
        description: ''
        example: 0175cc8f-2836-4f18-a45d-b055daac5ffd
        required: true
        schema:
          type: string
  /api/v1/phone:
    get:
      summary: ''
      operationId: getApiV1Phone
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: number
                  description: 'Must be at least 10. Must not be greater than 50.'
                  example: 11
                page:
                  type: number
                  description: 'Must be at least 1.'
                  example: 81
              required:
                - to
                - page
      security: []
    post:
      summary: ''
      operationId: postApiV1Phone
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: 'Must be at least 4 characters. Must not be greater than 16 characters.'
                  example: omjbsdvxmi
              required:
                - phone
      security: []
  '/api/v1/phone/{uuid}':
    get:
      summary: ''
      operationId: getApiV1PhoneUuid
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiV1PhoneUuid
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: 'Must be at least 4 characters. Must not be greater than 16 characters.'
                  example: yxkprqfmjeiuuvo
              required:
                - phone
      security: []
    delete:
      summary: ''
      operationId: deleteApiV1PhoneUuid
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: uuid
        description: ''
        example: 0175cc8f-2836-4f18-a45d-b055daac5ffd
        required: true
        schema:
          type: string
  /oauth/v1/login:
    get:
      summary: ''
      operationId: getOauthV1Login
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
  /oauth/v1/check:
    get:
      summary: ''
      operationId: getOauthV1Check
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /oauth/v1/logout:
    get:
      summary: ''
      operationId: getOauthV1Logout
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
